# Generated by Django 4.2.23 on 2025-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="is_sso_admin",
            field=models.BooleanField(
                default=False, verbose_name="是否为SSO平台管理员"
            ),
        ),
        migrations.AlterField(
            model_name="authuser",
            name="active_team_id",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="当前激活团队ID"
            ),
        ),
    ]
