# Generated by Django 4.2.23 on 2025-09-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_authuser_is_sso_admin_alter_authuser_active_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="sso_routes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="SSO路由信息"
            ),
        ),
    ]
