# Generated by Django 4.2.1 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='created_by',
        ),
        migrations.AddField(
            model_name='task',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='创建用户ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator_name',
            field=models.CharField(default='system', max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AddField(
            model_name='task',
            name='lock_version',
            field=models.IntegerField(default=0, verbose_name='乐观锁版本号'),
        ),
        migrations.AddField(
            model_name='task',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序值'),
        ),
        migrations.AddField(
            model_name='task',
            name='team_id',
            field=models.IntegerField(db_index=True, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(0, '调试任务'), (1, '普通任务')], default=0, verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='updater_id',
            field=models.IntegerField(default=0, verbose_name='更新用户ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='updater_name',
            field=models.CharField(default='system', max_length=50, verbose_name='更新用户名称'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='创建用户ID'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='creator_name',
            field=models.CharField(default='system', max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='lock_version',
            field=models.IntegerField(default=0, verbose_name='乐观锁版本号'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序值'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='team_id',
            field=models.IntegerField(db_index=True, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='updater_id',
            field=models.IntegerField(default=0, verbose_name='更新用户ID'),
        ),
        migrations.AddField(
            model_name='taskdevice',
            name='updater_name',
            field=models.CharField(default='system', max_length=50, verbose_name='更新用户名称'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='创建用户ID'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='creator_name',
            field=models.CharField(default='system', max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='lock_version',
            field=models.IntegerField(default=0, verbose_name='乐观锁版本号'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序值'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='team_id',
            field=models.IntegerField(db_index=True, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='updater_id',
            field=models.IntegerField(default=0, verbose_name='更新用户ID'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='updater_name',
            field=models.CharField(default='system', max_length=50, verbose_name='更新用户名称'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='创建用户ID'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='creator_name',
            field=models.CharField(default='system', max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='lock_version',
            field=models.IntegerField(default=0, verbose_name='乐观锁版本号'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序值'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='team_id',
            field=models.IntegerField(db_index=True, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='updater_id',
            field=models.IntegerField(default=0, verbose_name='更新用户ID'),
        ),
        migrations.AddField(
            model_name='taskscript',
            name='updater_name',
            field=models.CharField(default='system', max_length=50, verbose_name='更新用户名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskscript',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
