# Generated by Django 4.2.1 on 2025-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_created_by_remove_taskgroup_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='run_type',
            field=models.IntegerField(choices=[(0, '全部'), (1, '调试任务'), (2, '单次任务'), (3, '定时任务'), (4, '任务套件')], default=0, verbose_name='运行类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(choices=[(0, '全部'), (1, '回放')], default=0, verbose_name='任务类型'),
        ),
    ]
