# Generated by Django 4.2.1 on 2025-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_type_task_run_type_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='run_type',
            field=models.IntegerField(choices=[(0, '全部'), (1, '调试'), (2, '单次'), (3, '定时')], default=0, verbose_name='运行类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(choices=[(0, '全部'), (1, '回放任务')], default=0, verbose_name='任务类型'),
        ),
    ]
