# Generated by Django 4.2.1 on 2025-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_run_type_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='run_info',
            field=models.JSONField(blank=True, null=True, verbose_name='运行配置信息'),
        ),
    ]
