# Generated by Django 4.2.1 on 2025-10-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_run_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='创建用户ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_id',
            field=models.IntegerField(db_index=True, editable=False, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updater_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='更新用户ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updater_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='更新用户名称'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='creator_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='创建用户ID'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='creator_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='team_id',
            field=models.IntegerField(db_index=True, editable=False, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='updater_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='更新用户ID'),
        ),
        migrations.AlterField(
            model_name='taskdevice',
            name='updater_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='更新用户名称'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='creator_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='创建用户ID'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='creator_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='team_id',
            field=models.IntegerField(db_index=True, editable=False, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='updater_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='更新用户ID'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='updater_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='更新用户名称'),
        ),
        migrations.AlterField(
            model_name='taskscript',
            name='creator_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='创建用户ID'),
        ),
        migrations.AlterField(
            model_name='taskscript',
            name='creator_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='创建用户名称'),
        ),
        migrations.AlterField(
            model_name='taskscript',
            name='team_id',
            field=models.IntegerField(db_index=True, editable=False, help_text='标识数据归属的团队', null=True, verbose_name='团队ID'),
        ),
        migrations.AlterField(
            model_name='taskscript',
            name='updater_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='更新用户ID'),
        ),
        migrations.AlterField(
            model_name='taskscript',
            name='updater_name',
            field=models.CharField(default='system', editable=False, max_length=50, verbose_name='更新用户名称'),
        ),
    ]
