# Generated by Django 4.2.1 on 2025-10-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_creator_id_alter_task_creator_name_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_4a0a95_idx',
            old_name='ai_task_status_6243e0_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_priorit_a900d4_idx',
            old_name='ai_task_priorit_9df455_idx',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks_task',
        ),
        migrations.AlterModelTable(
            name='taskdevice',
            table='tasks_task_device',
        ),
        migrations.AlterModelTable(
            name='taskgroup',
            table='tasks_task_group',
        ),
        migrations.AlterModelTable(
            name='taskscript',
            table='tasks_task_script',
        ),
    ]
