# Generated by Django 4.2.1 on 2025-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_ai_task_status_6243e0_idx_tasks_task_status_4a0a95_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery任务ID'),
        ),
    ]
