# Generated by Django 4.2.1 on 2025-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_celery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='script_params',
            field=models.JSONField(blank=True, null=True, verbose_name='回放or其他脚本执行参数'),
        ),
    ]
