# Generated by Django 4.2.21 on 2025-07-23 14:59

import apps.ocr.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRGitRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, verbose_name="仓库URL")),
                (
                    "branch",
                    models.CharField(
                        default="main", max_length=100, verbose_name="默认分支"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "OCR Git仓库",
                "verbose_name_plural": "OCR Git仓库",
                "db_table": "ocr_git_repository",
            },
        ),
        migrations.CreateModel(
            name="OCRProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "OCR项目",
                "verbose_name_plural": "OCR项目",
                "db_table": "ocr_project",
            },
        ),
        migrations.CreateModel(
            name="OCRTask",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.ocr.models.generate_task_id,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("git", "Git仓库"), ("upload", "本地上传")],
                        max_length=10,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("config", models.JSONField(verbose_name="任务配置")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "total_images",
                    models.IntegerField(default=0, verbose_name="总图片数"),
                ),
                (
                    "matched_images",
                    models.IntegerField(default=0, verbose_name="匹配图片数"),
                ),
                (
                    "match_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="匹配率",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "git_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ocr.ocrgitrepository",
                        verbose_name="Git仓库",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="ocr.ocrproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR任务",
                "verbose_name_plural": "OCR任务",
                "db_table": "ocr_task",
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(max_length=255, verbose_name="图片路径"),
                ),
                ("texts", models.JSONField(verbose_name="识别文本")),
                (
                    "languages",
                    models.JSONField(blank=True, null=True, verbose_name="识别语言"),
                ),
                (
                    "has_match",
                    models.BooleanField(default=False, verbose_name="是否匹配"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="置信度",
                    ),
                ),
                (
                    "processing_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="处理时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ocr.ocrtask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR结果",
                "verbose_name_plural": "OCR结果",
                "db_table": "ocr_result",
            },
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="ocr.ocrproject",
                verbose_name="所属项目",
            ),
        ),
    ]
