# Generated by Django 4.2.23 on 2025-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrtask",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务名称"
            ),
        ),
    ]
