# Generated by Django 4.2.23 on 2025-08-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0002_ocrtask_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrgitrepository",
            name="token",
            field=models.CharField(default="", max_length=255, verbose_name="访问令牌"),
        ),
    ]
