# Generated by Django 4.2.1 on 2025-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_ocrgitrepository_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtask',
            name='git_branch',
            field=models.CharField(blank=True, default='main', max_length=100, null=True, verbose_name='Git分支'),
        ),
    ]
