# Generated by Django 4.2.1 on 2025-08-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_ocrtask_git_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtask',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='ocrtask',
            name='git_branch',
            field=models.CharField(blank=True, default='main', max_length=255, null=True, verbose_name='Git分支'),
        ),
    ]
