# Generated by Django 4.2.23 on 2025-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0005_ocrtask_remark_alter_ocrtask_git_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrgitrepository",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
    ]
