# Generated by Django 4.2.23 on 2025-09-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0006_ocrgitrepository_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrresult",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
        migrations.AlterField(
            model_name="ocrgitrepository",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="ocr.ocrproject",
                verbose_name="所属项目",
            ),
        ),
    ]
