# Generated by Django 4.2.1 on 2025-09-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_alter_ocrresult_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='pic_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='图片分辨率'),
        ),
    ]
