# Generated by Django 4.2.21 on 2025-09-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0007_ocrresult_team_id_ocrtask_team_id_and_more"),
        ("ocr", "0008_ocrresult_pic_resolution"),
    ]

    operations = []
