# Generated by Django 4.2.21 on 2025-09-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0009_merge_20250925_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrtask",
            name="processed_images",
            field=models.IntegerField(default=0, verbose_name="已处理图片数"),
        ),
    ]
