# Generated by Django 4.2.21 on 2025-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0010_ocrtask_processed_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrresult",
            name="image_hash",
            field=models.CharField(
                default="", max_length=128, verbose_name="图片哈希值"
            ),
        ),
    ]
