# Generated by Django 4.2.21 on 2025-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0011_ocrresult_image_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrgitrepository",
            name="creator_id",
            field=models.IntegerField(default=0, verbose_name="创建用户ID"),
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="creator_name",
            field=models.CharField(
                default="system", max_length=50, verbose_name="创建用户名称"
            ),
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="lock_version",
            field=models.IntegerField(default=0, verbose_name="乐观锁版本号"),
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注信息"),
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="排序值"),
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="updater_id",
            field=models.IntegerField(default=0, verbose_name="更新用户ID"),
        ),
        migrations.AddField(
            model_name="ocrgitrepository",
            name="updater_name",
            field=models.CharField(
                default="system", max_length=50, verbose_name="更新用户名称"
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="creator_id",
            field=models.IntegerField(default=0, verbose_name="创建用户ID"),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="creator_name",
            field=models.CharField(
                default="system", max_length=50, verbose_name="创建用户名称"
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="lock_version",
            field=models.IntegerField(default=0, verbose_name="乐观锁版本号"),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注信息"),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="排序值"),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="updater_id",
            field=models.IntegerField(default=0, verbose_name="更新用户ID"),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="updater_name",
            field=models.CharField(
                default="system", max_length=50, verbose_name="更新用户名称"
            ),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="creator_id",
            field=models.IntegerField(default=0, verbose_name="创建用户ID"),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="creator_name",
            field=models.CharField(
                default="system", max_length=50, verbose_name="创建用户名称"
            ),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="lock_version",
            field=models.IntegerField(default=0, verbose_name="乐观锁版本号"),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="排序值"),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="updater_id",
            field=models.IntegerField(default=0, verbose_name="更新用户ID"),
        ),
        migrations.AddField(
            model_name="ocrtask",
            name="updater_name",
            field=models.CharField(
                default="system", max_length=50, verbose_name="更新用户名称"
            ),
        ),
        migrations.AlterField(
            model_name="ocrgitrepository",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="ocrtask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
    ]
