# Generated by Django 4.2.21 on 2025-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0012_ocrgitrepository_creator_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRCache",
            fields=[
                (
                    "image_hash",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="图片MD5哈希",
                    ),
                ),
                (
                    "result_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="首次识别结果ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "OCR图片缓存",
                "verbose_name_plural": "OCR图片缓存",
                "db_table": "ocr_cache",
            },
        ),
        migrations.CreateModel(
            name="OCRCacheHit",
            fields=[
                (
                    "task_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="OCR任务ID",
                    ),
                ),
                (
                    "result_ids",
                    models.TextField(verbose_name="缓存命中结果ID列表，逗号分隔"),
                ),
            ],
            options={
                "verbose_name": "OCR缓存命中记录",
                "verbose_name_plural": "OCR缓存命中记录",
                "db_table": "ocr_cache_hit",
            },
        ),
        migrations.AlterField(
            model_name="ocrgitrepository",
            name="creator_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="创建用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="ocrgitrepository",
            name="creator_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="创建用户名称",
            ),
        ),
        migrations.AlterField(
            model_name="ocrgitrepository",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                editable=False,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
        migrations.AlterField(
            model_name="ocrgitrepository",
            name="updater_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="更新用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="ocrgitrepository",
            name="updater_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="更新用户名称",
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="creator_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="创建用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="creator_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="创建用户名称",
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                editable=False,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="updater_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="更新用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="updater_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="更新用户名称",
            ),
        ),
        migrations.AlterField(
            model_name="ocrtask",
            name="creator_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="创建用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="ocrtask",
            name="creator_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="创建用户名称",
            ),
        ),
        migrations.AlterField(
            model_name="ocrtask",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                editable=False,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
        migrations.AlterField(
            model_name="ocrtask",
            name="updater_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="更新用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="ocrtask",
            name="updater_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="更新用户名称",
            ),
        ),
    ]
