# Generated by Django 4.2.21 on 2025-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0013_ocrcache_ocrcachehit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrresult",
            name="confidence",
        ),
        migrations.AddField(
            model_name="ocrcache",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="是否人工校验"),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="confidences",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="各文本置信度列表"
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="corrected_texts",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="人工矫正文本"
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="ground_truth_origin_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="对比真值来源ID"
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="max_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0.0,
                max_digits=5,
                null=True,
                verbose_name="最高识别分数",
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="similarity_score",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=5, verbose_name="真值相似度"
            ),
        ),
        migrations.AlterField(
            model_name="ocrcachehit",
            name="result_ids",
            field=models.TextField(
                verbose_name="缓存命中结果ID列表，逗号分隔。例如：1,2,3"
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="result_type",
            field=models.IntegerField(
                choices=[(0, "待确认"), (1, "正确"), (2, "误检"), (3, "漏检")],
                default=0,
                verbose_name="识别结果类型",
            ),
        ),
    ]
