# Generated by Django 4.2.21 on 2025-11-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模型名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("ocr", "OCR"), ("yolo", "YOLO")],
                        default="ocr",
                        max_length=20,
                        verbose_name="模型类型",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="版本号")),
                (
                    "path",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="模型路径"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="模型描述"),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI模型",
                "verbose_name_plural": "AI模型",
                "db_table": "ai_model",
                "ordering": ["-created_at"],
            },
        ),
    ]
