# Generated by Django 4.2.21 on 2025-10-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        (
            "scripts",
            "0009_actionparam_actiontype_alter_scriptcategory_options_and_more",
        ),
        ("devices", "0003_device_android_version_device_brand_device_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        help_text="标识数据归属的团队",
                        null=True,
                        verbose_name="团队ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="创建用户ID"
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="创建用户名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updater_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="更新用户ID"
                    ),
                ),
                (
                    "updater_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="更新用户名称",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "lock_version",
                    models.IntegerField(default=0, verbose_name="乐观锁版本号"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="报告名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "生成失败"),
                        ],
                        default="generating",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "report_path",
                    models.CharField(max_length=500, verbose_name="报告路径"),
                ),
                (
                    "summary_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="汇总报告路径"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("duration", models.FloatField(verbose_name="持续时间(秒)")),
                (
                    "total_cases",
                    models.IntegerField(default=0, verbose_name="用例总数"),
                ),
                (
                    "passed_cases",
                    models.IntegerField(default=0, verbose_name="通过用例数"),
                ),
                (
                    "failed_cases",
                    models.IntegerField(default=0, verbose_name="失败用例数"),
                ),
                (
                    "error_cases",
                    models.IntegerField(default=0, verbose_name="错误用例数"),
                ),
                (
                    "skipped_cases",
                    models.IntegerField(default=0, verbose_name="跳过用例数"),
                ),
                ("success_rate", models.FloatField(default=0, verbose_name="成功率")),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="tasks.task",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "db_table": "report_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        help_text="标识数据归属的团队",
                        null=True,
                        verbose_name="团队ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="创建用户ID"
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="创建用户名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updater_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="更新用户ID"
                    ),
                ),
                (
                    "updater_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="更新用户名称",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "lock_version",
                    models.IntegerField(default=0, verbose_name="乐观锁版本号"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                ("result", models.CharField(max_length=50, verbose_name="执行结果")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("duration", models.FloatField(verbose_name="持续时间(秒)")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="截图路径"
                    ),
                ),
                (
                    "log_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="日志路径"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="reports.report",
                        verbose_name="报告",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scripts.script",
                        verbose_name="脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告详情",
                "verbose_name_plural": "报告详情",
                "db_table": "report_detail",
                "ordering": ["start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="report_repo_status_7d0999_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["success_rate"], name="report_repo_success_70ad63_idx"
            ),
        ),
    ]
