# Generated by Django 4.2.1 on 2025-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_reportdetail_script_reportdetail_step_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
