# Generated by Django 4.2.1 on 2025-11-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_start_end_remove_reportdetail_start_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdetail',
            options={'ordering': ['-created_at'], 'verbose_name': '报告详情', 'verbose_name_plural': '报告详情'},
        ),
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.FloatField(default=0, verbose_name='持续时间(秒)'),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='duration',
            field=models.FloatField(default=0, verbose_name='持续时间(秒)'),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='result',
            field=models.CharField(default='pending', max_length=50, verbose_name='执行结果'),
        ),
    ]
