# Generated by Django 4.2.21 on 2025-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_reportdetail_options_alter_report_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="success_rate",
            field=models.FloatField(default=0, verbose_name="c成功率"),
        ),
    ]
