# Generated by Django 4.2.1 on 2025-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_reportdetail_step_results_default_to_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='success_rate',
            field=models.FloatField(default=0, verbose_name='c成功率'),
        ),
    ]
