# Generated by Django 4.2.21 on 2025-05-15 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="脚本名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("record", "录制"),
                            ("manual", "手动"),
                            ("generated", "自动生成"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="脚本类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="脚本内容")),
                ("description", models.TextField(blank=True, verbose_name="脚本描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "execution_count",
                    models.IntegerField(default=0, verbose_name="执行次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试脚本",
                "verbose_name_plural": "测试脚本",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ScriptCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="scripts.scriptcategory",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本分类",
                "verbose_name_plural": "脚本分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时长(秒)"
                    ),
                ),
                ("result", models.TextField(blank=True, verbose_name="执行结果")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="scripts.script",
                        verbose_name="脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本执行记录",
                "verbose_name_plural": "脚本执行记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="script",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scripts",
                to="scripts.scriptcategory",
                verbose_name="所属分类",
            ),
        ),
        migrations.CreateModel(
            name="ScriptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="版本")),
                ("content", models.JSONField(default=dict, verbose_name="脚本内容")),
                ("comment", models.TextField(blank=True, verbose_name="版本说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="scripts.script",
                        verbose_name="脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本版本",
                "verbose_name_plural": "脚本版本",
                "ordering": ["-created_at"],
                "unique_together": {("script", "version")},
            },
        ),
        migrations.CreateModel(
            name="ScriptFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                ("file_size", models.IntegerField(default=0, verbose_name="文件大小")),
                ("step_count", models.IntegerField(default=0, verbose_name="步骤数量")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("record", "录制"),
                            ("manual", "手动"),
                            ("generated", "自动生成"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="脚本类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="文件描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "可用"), ("archived", "已归档")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="script_files",
                        to="scripts.scriptcategory",
                        verbose_name="所属分类",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本文件",
                "verbose_name_plural": "脚本文件",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["filename"], name="scripts_scr_filenam_839215_idx"
                    ),
                    models.Index(
                        fields=["status"], name="scripts_scr_status_a1d417_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="script",
            index=models.Index(fields=["name"], name="scripts_scr_name_b54d87_idx"),
        ),
        migrations.AddIndex(
            model_name="script",
            index=models.Index(fields=["type"], name="scripts_scr_type_97d6a2_idx"),
        ),
    ]
