# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptcategory",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="分类描述"),
        ),
        migrations.AlterField(
            model_name="scriptcategory",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="分类名称"
            ),
        ),
        migrations.AlterField(
            model_name="scriptcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="scripts.scriptcategory",
                verbose_name="父分类",
            ),
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("python_path", "Python解释器路径"),
                            ("device_timeout", "设备连接超时(秒)"),
                            ("ui_confidence", "UI识别置信度"),
                            ("yolo_model_path", "YOLO模型路径"),
                            ("default_loop_count", "默认循环次数"),
                            ("default_wait_timeout", "默认等待超时(秒)"),
                            ("report_keep_days", "报告保留天数"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="键名",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True, verbose_name="值")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "ordering": ["key"],
            },
        ),
    ]
