# Generated by Django 4.2.21 on 2025-10-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        (
            "scripts",
            "0009_actionparam_actiontype_alter_scriptcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        help_text="标识数据归属的团队",
                        null=True,
                        verbose_name="团队ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="创建用户ID"
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="创建用户名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updater_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="更新用户ID"
                    ),
                ),
                (
                    "updater_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="更新用户名称",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "lock_version",
                    models.IntegerField(default=0, verbose_name="乐观锁版本号"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="数据名称")),
                ("data", models.JSONField(verbose_name="数据内容")),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "数据记录",
                "verbose_name_plural": "数据记录",
                "db_table": "data_item",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        help_text="标识数据归属的团队",
                        null=True,
                        verbose_name="团队ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="创建用户ID"
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="创建用户名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updater_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="更新用户ID"
                    ),
                ),
                (
                    "updater_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="更新用户名称",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "lock_version",
                    models.IntegerField(default=0, verbose_name="乐观锁版本号"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="数据源名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("excel", "Excel文件"),
                            ("database", "数据库"),
                            ("api", "API接口"),
                            ("json", "JSON文件"),
                        ],
                        max_length=20,
                        verbose_name="数据源类型",
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="配置信息")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "数据源",
                "verbose_name_plural": "数据源",
                "db_table": "data_source",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        help_text="标识数据归属的团队",
                        null=True,
                        verbose_name="团队ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="创建用户ID"
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="创建用户名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updater_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="更新用户ID"
                    ),
                ),
                (
                    "updater_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="更新用户名称",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "lock_version",
                    models.IntegerField(default=0, verbose_name="乐观锁版本号"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
                ),
                ("result", models.CharField(max_length=50, verbose_name="使用结果")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "script",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scripts.script",
                        verbose_name="使用脚本",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                        verbose_name="所属任务",
                    ),
                ),
                (
                    "test_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="data_source.dataitem",
                        verbose_name="数据记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据使用日志",
                "verbose_name_plural": "数据使用日志",
                "db_table": "data_usage_log",
                "ordering": ["-used_at"],
            },
        ),
        migrations.AddField(
            model_name="dataitem",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_data",
                to="data_source.datasource",
                verbose_name="数据源",
            ),
        ),
        migrations.AddIndex(
            model_name="dataitem",
            index=models.Index(fields=["name"], name="data_item_name_3d63c7_idx"),
        ),
    ]
