# Generated by Django 4.2.21 on 2025-06-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="项目名称"
                    ),
                ),
                (
                    "yaml_path",
                    models.CharField(max_length=255, verbose_name="YAML配置路径"),
                ),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("inactive", "非活跃")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI项目监控",
                "verbose_name_plural": "AI项目监控",
                "db_table": "ai_projects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="ai_projects_name_c209f0_idx"),
                    models.Index(
                        fields=["status"], name="ai_projects_status_f5d8c3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "button_class",
                    models.CharField(max_length=50, verbose_name="按钮类名"),
                ),
                (
                    "scenario",
                    models.CharField(blank=True, max_length=100, verbose_name="场景"),
                ),
                ("success", models.BooleanField(verbose_name="执行成功")),
                (
                    "detection_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="检测时间(毫秒)"
                    ),
                ),
                (
                    "coordinates_x",
                    models.FloatField(blank=True, null=True, verbose_name="X坐标"),
                ),
                (
                    "coordinates_y",
                    models.FloatField(blank=True, null=True, verbose_name="Y坐标"),
                ),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="截图路径"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, max_length=50, verbose_name="设备ID"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="project_monitor.projectmonitor",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI执行记录",
                "verbose_name_plural": "AI执行记录",
                "db_table": "ai_execution_logs",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "button_class"],
                        name="ai_executio_project_d2dd86_idx",
                    ),
                    models.Index(
                        fields=["executed_at"], name="ai_executio_execute_13126a_idx"
                    ),
                    models.Index(
                        fields=["success"], name="ai_executio_success_2b827f_idx"
                    ),
                    models.Index(
                        fields=["button_class", "success"],
                        name="ai_executio_button__c3f417_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "button_class",
                    models.CharField(max_length=50, verbose_name="按钮类名"),
                ),
                (
                    "total_executions",
                    models.IntegerField(default=0, verbose_name="总执行次数"),
                ),
                (
                    "total_successes",
                    models.IntegerField(default=0, verbose_name="总成功次数"),
                ),
                (
                    "total_failures",
                    models.IntegerField(default=0, verbose_name="总失败次数"),
                ),
                (
                    "avg_detection_time_ms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="平均检测时间(毫秒)"
                    ),
                ),
                ("success_rate", models.FloatField(default=0.0, verbose_name="成功率")),
                (
                    "last_executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后执行时间"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_statistics",
                        to="project_monitor.projectmonitor",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI类统计",
                "verbose_name_plural": "AI类统计",
                "db_table": "ai_class_statistics",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["project", "button_class"],
                        name="ai_class_st_project_8e9546_idx",
                    ),
                    models.Index(
                        fields=["success_rate"], name="ai_class_st_success_18e01e_idx"
                    ),
                    models.Index(
                        fields=["last_executed_at"],
                        name="ai_class_st_last_ex_36f0f0_idx",
                    ),
                ],
                "unique_together": {("project", "button_class")},
            },
        ),
    ]
