# Generated by Django 4.2.21 on 2025-05-14 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="设备名称")),
                (
                    "device_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="设备ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("busy", "占用中"),
                            ("error", "故障"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(blank=True, max_length=50, verbose_name="IP地址"),
                ),
                (
                    "last_online",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后在线时间"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="设备描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="using_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当前使用者",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类型名称")),
                ("description", models.TextField(blank=True, verbose_name="类型描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备类型",
                "verbose_name_plural": "设备类型",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("critical", "严重"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="日志级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="日志内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备日志",
                "verbose_name_plural": "设备日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="devices.devicetype",
                verbose_name="设备类型",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_id"], name="devices_dev_device__e2c19e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_dev_status_bbf58f_idx"),
        ),
    ]
