# Generated by Django 4.2.21 on 2025-05-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="device",
            new_name="ai_device_device__88a0e8_idx",
            old_name="devices_dev_device__e2c19e_idx",
        ),
        migrations.RenameIndex(
            model_name="device",
            new_name="ai_device_status_8a187e_idx",
            old_name="devices_dev_status_bbf58f_idx",
        ),
        migrations.AlterModelTable(
            name="device",
            table="ai_device",
        ),
        migrations.AlterModelTable(
            name="devicelog",
            table="ai_devicelog",
        ),
        migrations.AlterModelTable(
            name="devicetype",
            table="ai_devicetype",
        ),
    ]
