# Generated by Django 4.2.21 on 2025-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "devices",
            "0002_rename_devices_dev_device__e2c19e_idx_ai_device_device__88a0e8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="android_version",
            field=models.CharField(blank=True, max_length=50, verbose_name="系统版本"),
        ),
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.CharField(blank=True, max_length=100, verbose_name="品牌"),
        ),
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.CharField(blank=True, max_length=100, verbose_name="型号"),
        ),
    ]
