# Generated by Django 4.2.21 on 2025-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_device_android_version_device_brand_device_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="height",
            field=models.IntegerField(default=0, verbose_name="屏幕高度"),
        ),
        migrations.AddField(
            model_name="device",
            name="width",
            field=models.IntegerField(default=0, verbose_name="屏幕宽度"),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "在线"),
                    ("offline", "离线"),
                    ("unauthorized", "未授权"),
                ],
                default="offline",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
