# Generated by Django 4.2.1 on 2025-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_height_device_width_alter_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_idle',
            field=models.BooleanField(default=True, verbose_name='是否空闲'),
        ),
    ]
