# Generated by Django 4.2.21 on 2025-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0002_alter_scriptcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="include_in_log",
            field=models.BooleanField(
                default=True,
                help_text="是否将执行结果包含在测试报告中",
                verbose_name="加入日志",
            ),
        ),
    ]
