# Generated by Django 4.2.21 on 2025-05-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0004_add_lifecycle_categories"),
    ]

    operations = []
