# Generated by Django 4.2.21 on 2025-05-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0002_add_lifecycle_categories"),
        ("scripts", "0005_add_lifecycle_categories"),
    ]

    operations = []
