# Generated by Django 4.2.21 on 2025-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0006_merge_20250528_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptfile",
            name="include_in_log",
            field=models.BooleanField(
                default=True,
                help_text="是否将执行结果包含在测试报告中",
                verbose_name="加入日志",
            ),
        ),
    ]
