# Generated by Django 4.2.21 on 2025-05-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0007_scriptfile_include_in_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="script",
            new_name="ai_script_name_a42299_idx",
            old_name="scripts_scr_name_b54d87_idx",
        ),
        migrations.RenameIndex(
            model_name="script",
            new_name="ai_script_type_2863d6_idx",
            old_name="scripts_scr_type_97d6a2_idx",
        ),
        migrations.RenameIndex(
            model_name="scriptfile",
            new_name="ai_script_f_filenam_940874_idx",
            old_name="scripts_scr_filenam_839215_idx",
        ),
        migrations.RenameIndex(
            model_name="scriptfile",
            new_name="ai_script_f_status_d1aa4c_idx",
            old_name="scripts_scr_status_a1d417_idx",
        ),
        migrations.AlterModelTable(
            name="script",
            table="ai_script",
        ),
        migrations.AlterModelTable(
            name="scriptcategory",
            table="ai_script_category",
        ),
        migrations.AlterModelTable(
            name="scriptexecution",
            table="ai_script_execution",
        ),
        migrations.AlterModelTable(
            name="scriptfile",
            table="ai_script_file",
        ),
        migrations.AlterModelTable(
            name="scriptversion",
            table="ai_script_version",
        ),
        migrations.AlterModelTable(
            name="systemconfig",
            table="ai_system_config",
        ),
    ]
