# Generated by Django 4.2.21 on 2025-09-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "scripts",
            "0008_rename_scripts_scr_name_b54d87_idx_ai_script_name_a42299_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        help_text="标识数据归属的团队",
                        null=True,
                        verbose_name="团队ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="创建用户ID"
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="创建用户名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updater_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="更新用户ID"
                    ),
                ),
                (
                    "updater_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="更新用户名称",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "lock_version",
                    models.IntegerField(default=0, verbose_name="乐观锁版本号"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="参数名")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("int", "整数"),
                            ("float", "小数"),
                            ("boolean", "布尔"),
                            ("array", "数组"),
                            ("object", "对象"),
                            ("enum", "枚举"),
                            ("json", "JSON"),
                            ("date", "日期"),
                            ("datetime", "日期时间"),
                            ("file", "文件"),
                            ("image", "图片"),
                        ],
                        max_length=20,
                        verbose_name="参数类型",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="是否必填"),
                ),
                (
                    "default",
                    models.JSONField(blank=True, null=True, verbose_name="默认值"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="参数描述"),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="参数英文描述"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="是否前端可见"),
                ),
                (
                    "editable",
                    models.BooleanField(default=True, verbose_name="是否可编辑"),
                ),
            ],
            options={
                "verbose_name": "动作参数",
                "verbose_name_plural": "动作参数",
                "db_table": "script_action_param",
                "ordering": ["action_library", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        help_text="标识数据归属的团队",
                        null=True,
                        verbose_name="团队ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="创建用户ID"
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="创建用户名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updater_id",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="更新用户ID"
                    ),
                ),
                (
                    "updater_name",
                    models.CharField(
                        default="system",
                        editable=False,
                        max_length=50,
                        verbose_name="更新用户名称",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "lock_version",
                    models.IntegerField(default=0, verbose_name="乐观锁版本号"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                (
                    "action_type",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="操作类型"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="操作名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="操作描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="操作图标"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="版本"
                    ),
                ),
            ],
            options={
                "verbose_name": "操作类型库",
                "verbose_name_plural": "操作类型库",
                "db_table": "script_action_type",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="scriptcategory",
            options={"verbose_name": "脚本分类", "verbose_name_plural": "脚本分类"},
        ),
        migrations.RenameIndex(
            model_name="script",
            new_name="script_scri_name_1abac9_idx",
            old_name="ai_script_name_a42299_idx",
        ),
        migrations.RenameIndex(
            model_name="script",
            new_name="script_scri_type_d49766_idx",
            old_name="ai_script_type_2863d6_idx",
        ),
        migrations.RemoveField(
            model_name="script",
            name="author",
        ),
        migrations.RemoveField(
            model_name="script",
            name="content",
        ),
        migrations.AddField(
            model_name="script",
            name="creator_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="创建用户ID"
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="creator_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="创建用户名称",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="lock_version",
            field=models.IntegerField(default=0, verbose_name="乐观锁版本号"),
        ),
        migrations.AddField(
            model_name="script",
            name="meta",
            field=models.JSONField(blank=True, default=dict, verbose_name="元数据"),
        ),
        migrations.AddField(
            model_name="script",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注信息"),
        ),
        migrations.AddField(
            model_name="script",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="排序值"),
        ),
        migrations.AddField(
            model_name="script",
            name="steps",
            field=models.JSONField(blank=True, default=list, verbose_name="步骤列表"),
        ),
        migrations.AddField(
            model_name="script",
            name="steps_count",
            field=models.IntegerField(default=0, verbose_name="步骤数量"),
        ),
        migrations.AddField(
            model_name="script",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                editable=False,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="updater_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="更新用户ID"
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="updater_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="更新用户名称",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="version",
            field=models.CharField(default="1.0", max_length=50, verbose_name="版本"),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="creator_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="创建用户ID"
            ),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="creator_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="创建用户名称",
            ),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="lock_version",
            field=models.IntegerField(default=0, verbose_name="乐观锁版本号"),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注信息"),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="排序值"),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="team_id",
            field=models.IntegerField(
                db_index=True,
                editable=False,
                help_text="标识数据归属的团队",
                null=True,
                verbose_name="团队ID",
            ),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="updater_id",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="更新用户ID"
            ),
        ),
        migrations.AddField(
            model_name="scriptcategory",
            name="updater_name",
            field=models.CharField(
                default="system",
                editable=False,
                max_length=50,
                verbose_name="更新用户名称",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="scriptcategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="scriptcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="分类名称"),
        ),
        migrations.AlterModelTable(
            name="script",
            table="script_script",
        ),
        migrations.AlterModelTable(
            name="scriptcategory",
            table="script_category",
        ),
        migrations.AlterModelTable(
            name="scriptexecution",
            table="script_execution",
        ),
        migrations.AlterModelTable(
            name="scriptversion",
            table="script_version",
        ),
        migrations.AddField(
            model_name="actionparam",
            name="action_library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="params",
                to="scripts.actiontype",
                verbose_name="所属操作类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actionparam",
            unique_together={("action_library", "name")},
        ),
    ]
